name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          
      - name: Flutter get packages
        run: flutter pub get 

      - name: Run tests
        run: flutter test

      - name: Flutter build Android
        run: flutter build apk
        
      - name: Flutter build web
        run: flutter build web

      - name: Flutter build iOS
        run: flutter build ios

      - name: Flutter build Windows
        run: flutter config --enable-windows-desktop & flutter build windows

      - name: Flutter build Linux
        run: flutter config --enable-linux-desktop & flutter build linux

      - name: Flutter build macOS
        run: flutter config --enable-macos-desktop & flutter build macos

